### ISSUE TITLE
ACPI Exception: AE_NOT_FOUND lookup/catalog 20160930/psobject-310

### ISSUE THREAD

**Issue by ramcla** [jaehxx0925/X1C7-Hackintosh#1]
dear jaehxx0925,

thanks for your shearing.

I try it on my x1c7 TP00109A 20QD-S2C900
but when I try to boot via cloover in Mac I get the error below 

_ACPI Error : [_SB_.PC10.XHC_.RHUB.HS14] NameSpace lookup failure, AE_NOT_FOUND (20160930/dswload2-274_

but the booting continu until

ACPI Exception: AE_NOT_FOUND lookup/catalog 20160930/psobject-310
ACPI Error: Method parse/execution failed [\] (node ffffff7f936a8720), AE_NOT_FOUND (20160930/parse-632)
ACPI : Exeucted 38 blocks of module-level executable AML code

could you help me ?

regards

**Comment by jaehxx0925** [comment]
First, I'm not an hacktintosh expert, so I can't give you the exact solution.
Remember this build is not complete, so getting ACPI Errors are normal at this step. 

I'm getting ACPI Errors in my X1C7 too, but It has no problem at booting. 
So, try waiting 3-4mins when ACPI Error shows up.

First one seems it's USB (XHCI) related error, try using USBInjectAll.kext from RehabMan. 

However, patched DSDT must used with exact same model. Your model number doesn't match with me. Try with ACPI/patched/DSDT.aml erased.

**Comment by ramcla** [comment]
dear jeahxx0925,
thanks for your quick response ;-)
I just test your solution and I successfully boot on catalina installer
I will keep you informed
regards
ramcla

**Comment by pierolsl** [comment]
Dear all,
I got the same ACPI error, and I've tested the solution above, but it didn't boot on the installer, it took more than 10 mins...
If I use my own DSDT.aml, I'll get lots of errors, could you tell me which patches do you patch to your DSDT.aml?

regards,
pierolsl

**Comment by pierolsl** [comment]
Dear jaehxx0925,
Thanks for your sharing.
Based on your DSDT.aml and config.plist, I've installed the Catalina, but the booting time is more than 20 mins, so could you tell me the pacth list you choose?
Thanks a lot.

Regards,
pierolsl

**Comment by jaehxx0925** [comment]
> Dear jaehxx0925,
> Thanks for your sharing.
> Based on your DSDT.aml and config.plist, I've installed the Catalina, but the booting time is more than 20 mins, so could you tell me the pacth list you choose?
> Thanks a lot.
> 
> Regards,
> pierolsl

Check Laptop DSDT patch guide by RehabMan.

I applied common patches, brightness fix and battery patch for Lenovo X230i.

https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/

**Comment by ramcla** [comment]
hi,
on my x1c7 20QD S2C900
DSDT patch works for battery patch (lenovo X230i) but not with brightness fix
no SSDT at all 
only config of Mr jaehxx0925 (thanks to him :-)) 
audio output is ok but no input 
web cam ok
WiFi with dongle EDIMAX
regards

**Comment by pierolsl** [comment]
Hi all,
I found the reason of this booting delay issue, select the "Fix Regions" item in DSDT Fixes, then booting speed "boom boom boom".
According to https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/ about Floating Regions

Regards,
pierolsl
